### ISSUE TITLE
Question: Adding PVP-Events only to specific instance

### ISSUE THREAD

**Issue by muelleel** [TogAr2/MinestomPvP#17]
Hey, I'm trying to get get PVP on an specific instance working.

Minestom's `eventNode.appendChild` within an Instance accepts as an Parameter
`EventNode<? extends InstanceEvent>`

MinestomPvp returs from `PvpExtension.legacyEvents()` or the new Builder `EventNode
<EntityEvent>`

In all examples are always global event listener used, is there a way to register pvp events on specific Instances or even only players?

Thanks!

**Comment by TogAr2** [comment]
Using the latest commit, you should now be able to do `instance.eventNode().addChild(PvpExtension.legacyEvents()`!
