### ISSUE TITLE
Projectiles desync between client and server

### ISSUE THREAD

**Issue by mmm1245** [TogAr2/MinestomPvP#21]
when shooting projectiles(tested with snowballs and arrows), they are rubberbanding

**Comment by TogAr2** [comment]
Can you attach a video of the rubberbanding?

**Comment by mmm1245** [comment]
https://www.youtube.com/watch?v=0624HBfQ298&ab_channel=mmm

**Comment by TogAr2** [comment]
Interesting, it doesn't happen for me inside the test project. Are you sure you're not cancelling any movement or doing something else with the projectile that could be interfering?
If you are sure this is a problem with MinestomPvP, I would like to have a reproducer, since I can't reproduce it myself

**Comment by TogAr2** [comment]
Also make sure you're not registering MinestomPvP twice or have multiple MinestomPvP event listeners on the same node, it is known to cause trouble

**Comment by mmm1245** [comment]
repository: https://github.com/IndustrialCraft/Minestom-Server
also, i am  registering it only once after calling init(in MinestomBootstrap.java)

**Comment by TogAr2** [comment]
Your instance doesn't seem to be registered
I am not sure how because clearly you're registering it, but you can check for yourself: `MinecraftServer.getInstanceManager().getInstances()` has a size of 0

**Comment by TogAr2** [comment]
It causes the worldborder to not tick, so it's diameter is always set to 0

**Comment by TogAr2** [comment]
Oh I see, you're creating the `InstanceManager` yourself
You should use `MinecraftServer.getInstanceManager()`

**Comment by mmm1245** [comment]
that fixed it, thank you for your help
