### ISSUE TITLE
FinallAttack Bug?

### ISSUE THREAD

**Issue by xImNoxh** [TogAr2/MinestomPvP#24]
Hello, I have the following problem...
If I want to hit a player it only works 2-3 times then it doesn't work anymore. It only works if the player I want to hit gets damaged again by something else (e.g. falling damage) In my opinion this is not normal xD

**Comment by TogAr2** [comment]
Hey! This is quite some time ago (I wasn't looking after this project). If this issue is still relevant please open another issue describing exactly what you are doing (give a minimal code example).
