### ISSUE TITLE
Arrow not shooting from bow and crossbow

### ISSUE THREAD

**Issue by Zenqrt** [TogAr2/MinestomPvP#39]
When trying to shoot an arrow from a bow or crossbow, no arrow shoots or gets used.

This happens when registering either CombatFeatures.modernVanilla() or CombatFeatures.VANILLA_PROJECTILE_ITEM and CombatFeatures.VANILLA_BOW (or crossbow).

**Comment by TogAr2** [comment]
Are you sure you are using the latest Minestom version? This is a recently fixed bug in Minestom

**Comment by Zenqrt** [comment]
I updated it to the latest commit, and it works now. Thank you!
