### ISSUE TITLE
[FEATURE] Subdividing the VANILLA_EXPLOSION to allow further customization

### ISSUE THREAD

**Issue by Andrei965** [TogAr2/MinestomPvP#40]
Currently, the VANILLA_EXPLOSION handles different things, such as end crystals, flint and steel, fire charges, etc...
It would be beneficial to further subdivide it (end crystals being separate...) or at least expose the VanillaExplosionSupplier. This would enable custom entities (for example, the Hypixel Bedwars fireball) to use the explosion supplier, without needing to add all of the other VANILLA_EXPLOSION features.

**Comment by TogAr2** [comment]
`ExplosionFeature` has now been subdivided into `ExplosionFeature` and `ExplosiveFeature`. The former (still) contains the explosion supplier, the latter now contains the logic for tnt, crystals and respawn anchors.

If you want to only use a certain type of explosive you can use the new events `AnchorChargeEvent`, `AnchorExplodeEvent`, `CrystalPlaceEvent` and `ExplosivePrimeEvent` to cancel the behavior
