### ISSUE TITLE
Falling of 4 blocks doesn't give fall damage

### ISSUE THREAD

**Issue by CodeDoctorDE** [TogAr2/MinestomPvP#41]
My code:
```kotlin
fun main() {
    val server = MinecraftServer.init()
    MinestomPvP.init()
    val instanceManager = MinecraftServer.getInstanceManager()
    val instanceContainer = instanceManager.createInstanceContainer()
    val path = Path.of("worlds/world")
    println(path.toAbsolutePath())
    instanceContainer.chunkLoader = AnvilLoader(path)
    val globalEventHandler = MinecraftServer.getGlobalEventHandler()
    globalEventHandler.addListener(AsyncPlayerConfigurationEvent::class.java) { event ->
        val player = event.player
        event.spawningInstance = instanceContainer
        player.respawnPoint = Pos(0.0, 17.0, 0.0)
    }
    val modernVanilla = CombatFeatures.modernVanilla()
    MinecraftServer.getGlobalEventHandler().addChild(modernVanilla.createNode())
    server.start("0.0.0.0", 25565)
    OpenToLAN.open()
}
```

If I fall of a 4 stone brick wall I get the "no fall damage" sound and doesn't loose any health. In vanillla, you will get 1 heart of damage.

Additionally when joining I also get the "no fall damage" sound.

**Comment by TogAr2** [comment]
Are you sure the "no fall damage" sound is caused by MinestomPvP? It could be client side. It could also be you're spawning the player a few blocks above the ground. I cannot think of any reason why MinestomPvP would play this sound on join

**Comment by TogAr2** [comment]
Other than that, the issue has been solved

**Comment by CodeDoctorDE** [comment]
> Are you sure the "no fall damage" sound is caused by MinestomPvP? It could be client side. It could also be you're spawning the player a few blocks above the ground. I cannot think of any reason why MinestomPvP would play this sound on join

No this can't be it. I have a flatworld like world and there is this sound too.



> Other than that, the issue has been solved

Nice thanks. Maybe it also solves the first issue

**Comment by TogAr2** [comment]
Did you test without enabling fall damage to see if the issue persists?

**Comment by CodeDoctorDE** [comment]
Okay, looks like the issue doesn't exist anymore. I close this issue. Thanks for fixing!

**Comment by CodeDoctorDE** [comment]
Okay, I tested it and you get 2 hearts of damage from a 4 block jump but you should only get 1 removed

**Comment by TogAr2** [comment]
I tested this before and it seems to align with vanilla. Is it not the same for you in vanilla?

**Comment by CodeDoctorDE** [comment]
Oh you are right, looks like this is really a vanilla feature.
I was thinking 3 block + jump = 4 block but this isn't the case
