### ISSUE TITLE
Player looses hunger very fast

### ISSUE THREAD

**Issue by CodeDoctorDE** [TogAr2/MinestomPvP#43]
I don't know how to mesure it but the hunger level gets lower after ~ 20 blocks sprinting. It doesn't feel vanilla like

**Comment by BatuhanAcikgoz** [comment]
Have you tried setting the difficulty to Normal? Maybe you are on Hard difficulty

**Comment by CodeDoctorDE** [comment]
I'm using the default difficulty for my instance (it's normal)

**Comment by BatuhanAcikgoz** [comment]
Yes, there is indeed a problem, it runs out very quickly. There is problem on ExhaustionFeature

**Comment by TogAr2** [comment]
Are you perhaps using legacy exhaustion? That would explain this issue since it is also the case in singleplayer 1.8

**Comment by CodeDoctorDE** [comment]
Yeah, can I fix this somehow or make this modern?

**Comment by TogAr2** [comment]
Using the latest commit you can add an override to your `CombatConfiguration`.
For example:
```java
CombatFeatureSet featureSet = CombatFeatures.getVanilla(CombatVersion.LEGACY, DifficultyProvider.DEFAULT)
        .add(CombatFeatures.VANILLA_EXHAUSTION, FeatureConfiguration.of(FeatureType.VERSION, CombatVersion.MODERN))
        .build();
```

This will overwrite the default vanilla exhaustion feature with a different one configured to use the modern value.

**Comment by CodeDoctorDE** [comment]
![Screenshot_20240801_215636](https://github.com/user-attachments/assets/89b97d53-9d99-4edf-bd93-a1849a26cef3)
Hmm, I wanted to test it but now the sword doesn't get ready in the legacy pvp anymore

**Comment by CodeDoctorDE** [comment]
Okay, i tested it and the hunger works now very good. Thank you for your help!
