### ISSUE TITLE
How can i check if a player was killed by another player or anything else?

### ISSUE THREAD

**Issue by m4rekdev** [TogAr2/MinestomPvP#52]
Hi,
   I'm making a minigame using MinestomPvP and was wondering how can i check if the player killed themselves (or anything else) or if they were killed by another player. I also want to get the killer (if theres one), so i can reward them for a kill. How can i do this?

**Comment by TogAr2** [comment]
In  a listener for`EntityDamageEvent` (or `FinalAttackEvent` when MinestomPvP specific logic is required), use `event.getDamage()`. From this object it is possible to get the direct damager (e.g. the arrow for a bowshot) or the attacker (e.g. the player shooting the bow, or the player using their sword).

**Comment by m4rekdev** [comment]
Doesn't that fire for every hit? How can i tell if the player was killed?

**Comment by TogAr2** [comment]
I'm sorry for apparently not being able to read 🤣

It is possible to use `LivingEntity#getLastDamageSource()` to get the last Damage object.

**Comment by TogAr2** [comment]
Using the latest commit, it is also possible to get the damage source from `EntityPreDeathEvent`.

On a side note: if you want to cancel the death (for example switch the player to spectator mode instead of actually killing them), you should use `EntityPreDeathEvent#setCancelDeath()`, because it will make sure the attack sounds and other effects are not cancelled.

**Comment by m4rekdev** [comment]
Thanks. Also, I need to kill the player when they touch water (im making gungame). How can i check if someone hhit them to the water or they jumped there by themselves? Can i somehow reset the last damage source after a few seconds of not receiving any damage?

**Comment by TogAr2** [comment]
It would be best to just keep track of the incoming hits (paired by the time) by yourself, in a list or something. You could add entries inside a listener for the damage event.

**Comment by m4rekdev** [comment]
So i need to create an external hashmap with the player username and the damage source with time?

**Comment by TogAr2** [comment]
You can also use a tag on the player.
https://minestom.net/docs/feature/tags

**Comment by m4rekdev** [comment]
Oh sorry i didnt know these existed. This can also cleanup my build mode code :D Thanks

**Comment by TogAr2** [comment]
Yep, and be sure to use Tag.Transient to avoid unnecessary serialization
