### ISSUE TITLE
Disable player knockback on respawn

### ISSUE THREAD

**Issue by m4rekdev** [TogAr2/MinestomPvP#53]
Hi, I already tried to set the player's velocity to 0, but that doesn't work. How can I do it?

**Comment by TogAr2** [comment]
Cancel `EntityKnockbackEvent`?

**Comment by m4rekdev** [comment]
How can i check if it was the last knockback? i cant seem to get 0 health from the event

```
20.0
15.5
10.333333
6.833333
2.833333
3.1666665
```

this is the health output of killing a player

**Comment by TogAr2** [comment]
That should not usually happen, maybe send me the code on discord so I can try to help. This is not really the right place for troubleshooting

**Comment by m4rekdev** [comment]
_fixed on discord_
